### PR TITLE
Added enable_upgrades flag instead of hardcoding in template

### PR DESCRIPTION
**Pull request by mynamewastaken**

### CODE REVIEW

**Comment by mcary** [comment]
This PR changes the default behavior to not actually upgrade.  How would you feel about preserving the default behavior by flipping enable_upgrades in attributes/default.rb?

Also, I would prefer to have these squashed into one commit because, while the first two commits don't leave the cookbook broken, there is little rationale for adding an unused attribute or passing it to the template without using it.  I can assist with the squashing if that would be helpful.

Finally, I would like to see the new attribute documented in README.rdoc and metadata.rb.

**Comment by mynamewastaken** [comment]
I can do that, give me a bit.

**Comment by mynamewastaken** [comment]
@mcary Flipped the default for enable_upgrades and added that documentation to the rdoc file. If you like the changes and are able to squash that would be great. The web interface apparently won't let me do it.

**Comment by mynamewastaken** [comment]
Forgot the metadata.rb. Should be good, now.

**Comment by mcary** [comment]
Thanks!  Tests passed.  I squashed these into one commit on [enable-upgrades-flag](https://github.com/mcary/unattended_upgrades/tree/enable-upgrades-flag) and merged it to master w/ version bump.

I'm still working on uploading a new version to supermarket.chef.io.  Are you waiting for that?

**Comment by mynamewastaken** [comment]
Cool, thanks.

Nope, just ran into an issue at work where we stopped using the
cookbook but one of our servers was still doing unattended upgrades. I
figured I would contribute back some of the changes I made upstream.

**Comment by mcary** [comment]
I uploaded the new version (0.2.0) to supermarket.chef.io: [unattended_upgrades](https://supermarket.chef.io/cookbooks/unattended_upgrades).

Closing, as these changes have been merged in squashed form.

**Pull request closed without merging**
